//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CombinedBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int Id { get; set; }
        public string VehicleName { get; set; }
        public int Capacity { get; set; }
        public int Quantity { get; set; }
        public string Branch { get; set; }
        public string Description { get; set; }
        public string Year { get; set; }
        public string Image { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<bool> Roaster { get; set; }
    }
}
